set -g allow-passthrough on
set-option -g default-shell /bin/bash
set-option -g default-command /bin/bash

set -g mouse on

set -g history-limit 50000

set -g status-interval 1
set -g status-position bottom

bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

set -s escape-time 0
